### ISSUE TITLE
'How to contribute' Section is missing in README 

### ISSUE THREAD

**Issue by Gansito144** [algoristas/dashboard#4]
Please provide a detailed information on how can others contribute to this project.

**Comment by rendon** [comment]
Thanks @Gansito144 I'll take care of this as soon as I can, quite important indeed.

**Comment by Gansito144** [comment]
Is there anyone taking care of this right now?

**Comment by rendon** [comment]
No, is this about inviting users to contribute or about explaining the setup to start contributing?

**Comment by Gansito144** [comment]
According to the issue is for the first one, a quick explanation of contribution process.

**Comment by rendon** [comment]
I think it's important but it's not priority, it can wait a bit more.

**Comment by Gansito144** [comment]
Fixed by #9
