### ISSUE TITLE
Add a page to show all problems for all weeks

### ISSUE THREAD

**Issue by xiddw** [algoristas/dashboard#8]
Right now, the dashboard only supports displaying the list of problems assigned for a specific week, so it's difficult to get an overall view of the complete list of problems, 

![weekly_allweeks](https://user-images.githubusercontent.com/742519/31050747-622516ce-a609-11e7-853a-f905bfa47f10.PNG)

A proposed implementation for this would be to have an additional option on the `Weekly problem set` drop-down that shows `All weeks` , and when that option is selected, displayed all the problems listed under all the weeks. 

An extra consideration is that right now each problem set uses the same numeration for the list of problems included, so that ideally this new table should show both the `Week #` and `Problem #`.

**Comment by rendon** [comment]
That would be the whole problem set, right? We could make this a new section, "Problems" or "All problems" or "Problem set", what do you think?

**Comment by xiddw** [comment]
Yeah, a new section could be also an option.  I personally do not have a strong preference, so either way sounds good.

**Comment by hopkins0** [comment]
The current version has implemented this feature.
